# -*- coding: utf-8 -*-
"""fake-news-classification-using-random-forest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ahpCnfSwOxRA5LuzLqRYj4NK0EUhcyWX
"""
# pip install -U scikit-learn
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import re
import string

data_fake = pd.read_csv('/content/Fake.csv')
data_true = pd.read_csv('/content/True.csv')

data_fake['class'] = 0
data_true['class'] = 1

data_fake.shape, data_true.shape

data_fake_manual_testing = data_fake.tail(10)
for i in range (23480,23470, -1):
  data_fake.drop([i], axis = 0, inplace = True)

data_true_manual_testing = data_true.tail(10)
for i in range (21416, 21406, -1):
  data_true.drop([i], axis = 0, inplace = True)

data_fake.shape, data_true.shape

data_fake_manual_testing['class'] = 0
data_true_manual_testing['class'] = 1

data_fake_manual_testing.head(10)

data_merge = pd.concat([data_fake, data_true], axis = 0)
data_merge.head(10)

data_merge.columns

data = data_merge.drop(['title', 'subject', 'date'], axis = 1)

data.isnull().sum()

data = data.sample(frac = 1)

data.head(5)

data.reset_index(inplace = True)
data.drop(['index'], axis = 1, inplace = True)

data.columns

def wordopt(text):
  text = text.lower ()
  text = re.sub('\[. *?\]','',text)
  text = re.sub("\\W"," ",text)
  text = re.sub('https?://\S+|www\.\S+', '', text)
  text = re.sub('<.*?›+', '', text)
  text = re.sub('[%s]' % re.escape(string.punctuation),'', text)
  text = re.sub( "\n",' ',text)
  text = re.sub('\w*\d\w*','',text)
  return text

data['text'] = data['text'].apply(wordopt)

x = data['text']
y = data['class']

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size= 0.25,random_state=42)

from sklearn.feature_extraction.text import TfidfVectorizer

vectorization = TfidfVectorizer ()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(random_state = 0)
RF.fit(xv_train, y_train)

pred_rf = RF.predict(xv_test)

RF.score(xv_test, y_test)

print(classification_report(y_test, pred_rf))

def output_label(n):
  if n == 0:
    return "Fake News"
  elif n == 1:
    return "Not A Fake News"

def manual_testing (news):
  testing_news = {"text": [news]}
  new_def_test = pd.DataFrame(testing_news)
  new_def_test["text"] = new_def_test["text"].apply(wordopt)
  new_x_test = new_def_test[ "text"]
  new_xv_test = vectorization.transform(new_x_test)
  pred_RF = RF.predict(new_xv_test)
  return print("In RF Prediction: {}".format(output_label(pred_RF[0])))

news = str(input())

"""The Pentagon is considering a Boeing proposal to supply Ukraine with cheap, small precision bombs fit ted on to abundantly available rockets, allowing Kyiv to strike far behind Russian lines, according t o a Reuters report. US and allied military inventories are shrinking, and Ukraine faces an increasin g need for more sophisticated weapons as the war drags on. Boeing's proposed system, dubbed Ground- La unched Small Diameter Bomb (GLSDB), is one of about a half-dozen plans for getting new munitions into
production for Ukraine and America's eastern European allies, industry sources told the news agency.
GLSDB could be delivered as early as spring 2023, according to a document reviewed by Reuters and thr ee people familiar with the plan. It combines the GBU-39 Small Diameter Bomb (SDB) with the M26 rocke t motor, both of which are common in US inventories. Although a handful of GLSDB units have already been made, there are many logistical obstacles to formal procurement. The Boeing plan requires a pric e discovery waiver, exempting the contractor from an in-depth review that ensures the Pentagon is get ting the best deal possible. Any arrangement would also require at least six suppliers to expedite sh ipments of their parts and services to produce the weapon quickly. Although the US has rebuffed requ ests for the 185-mile (297km) range Atacms missile, the GLSDB's 94-mile (150km) range would allow Ukr aine to hit valuable military targets that have been out of reach and help it continue pressing its c ounterattacks by disrupting Russian rear areas. GLSDB is made jointly by Saab AB and Boeing Co and h as been in development since 2019, well before the invasion, which Russia calls a "special operatio n". In October, SAAB chief executive Micael Johansson said of the GLSDB: "We are imminently shortly e xpecting contracts on that." According to the document - a Boeing proposal to US European - has smal 1, folding wings that allow it to glide more than 100km if dropped from an aircraft and targets as sm
all as 3ft in diameter.
"""

manual_testing(news)